import { iamRepository } from '@/services/iam/repository';
import type {
  AssignRoleInput,
  CreatePolicyInput,
  CreateUserInput,
  DelegateAccessInput,
  EndBreakGlassInput,
  GrantConsentInput,
  IamFilters,
  InviteUserInput,
  RevokeSessionInput,
  ShareIamInput,
  StartBreakGlassInput,
} from '@/services/iam/types';

const DELAY = 250;
async function delay(ms = DELAY) { await new Promise((r) => setTimeout(r, ms)); }

export const iamService = {
  async dashboard(tenantId?: string) { await delay(); return iamRepository.dashboard(tenantId); },
  async analytics(tenantId?: string) { await delay(); return iamRepository.analytics(tenantId); },
  async getUsers(filters?: IamFilters) { await delay(); return iamRepository.getUsers(filters); },
  async getUser(userId: string) { await delay(); return iamRepository.getUser(userId); },
  async getTenants(filters?: IamFilters) { await delay(); return iamRepository.getTenants(filters); },
  async getOrganizations(filters?: IamFilters) { await delay(); return iamRepository.getOrganizations(filters); },
  async getRoles(filters?: IamFilters) { await delay(); return iamRepository.getRoles(filters); },
  async getPermissions(filters?: IamFilters) { await delay(); return iamRepository.getPermissions(filters); },
  async getPolicies(filters?: IamFilters) { await delay(); return iamRepository.getPolicies(filters); },
  async getSessions(filters?: IamFilters) { await delay(); return iamRepository.getSessions(filters); },
  async getLoginHistory(filters?: IamFilters) { await delay(); return iamRepository.getLoginHistory(filters); },
  async getMfaDevices(filters?: IamFilters) { await delay(); return iamRepository.getMfaDevices(filters); },
  async getTrustedDevices(filters?: IamFilters) { await delay(); return iamRepository.getTrustedDevices(filters); },
  async getOauthClients(filters?: IamFilters) { await delay(); return iamRepository.getOauthClients(filters); },
  async getApiKeys(filters?: IamFilters) { await delay(); return iamRepository.getApiKeys(filters); },
  async getConsents(filters?: IamFilters) { await delay(); return iamRepository.getConsents(filters); },
  async getDelegations(filters?: IamFilters) { await delay(); return iamRepository.getDelegations(filters); },
  async getProxyAccess(filters?: IamFilters) { await delay(); return iamRepository.getProxyAccess(filters); },
  async getBreakGlass(filters?: IamFilters) { await delay(); return iamRepository.getBreakGlass(filters); },
  async getAuditEvents(filters?: IamFilters) { await delay(); return iamRepository.getAuditEvents(filters); },
  async getSecurityIncidents(filters?: IamFilters) { await delay(); return iamRepository.getSecurityIncidents(filters); },
  async getRiskScores(filters?: IamFilters) { await delay(); return iamRepository.getRiskScores(filters); },
  async getSamlProviders(filters?: IamFilters) { await delay(); return iamRepository.getSamlProviders(filters); },
  async getOidcProviders(filters?: IamFilters) { await delay(); return iamRepository.getOidcProviders(filters); },

  async createUser(input: CreateUserInput) { await delay(); return iamRepository.createUser(input); },
  async inviteUser(input: InviteUserInput) { await delay(); return iamRepository.inviteUser(input); },
  async lockAccount(userId: string) { await delay(); return iamRepository.lockAccount(userId); },
  async unlockAccount(userId: string) { await delay(); return iamRepository.unlockAccount(userId); },
  async assignRole(input: AssignRoleInput) { await delay(); return iamRepository.assignRole(input); },
  async removeRole(input: AssignRoleInput) { await delay(); return iamRepository.removeRole(input); },
  async createPolicy(input: CreatePolicyInput) { await delay(); return iamRepository.createPolicy(input); },
  async enableMfa(userId: string) { await delay(); return iamRepository.enableMfa(userId); },
  async disableMfa(userId: string) { await delay(); return iamRepository.disableMfa(userId); },
  async revokeSession(input: RevokeSessionInput) { await delay(); return iamRepository.revokeSession(input); },
  async createOAuthClient(name: string, tenantId: string) { await delay(); return iamRepository.createOAuthClient(name, tenantId); },
  async rotateApiKey(keyId: string) { await delay(); return iamRepository.rotateApiKey(keyId); },
  async grantConsent(input: GrantConsentInput) { await delay(); return iamRepository.grantConsent(input); },
  async revokeConsent(consentId: string) { await delay(); return iamRepository.revokeConsent(consentId); },
  async delegateAccess(input: DelegateAccessInput) { await delay(); return iamRepository.delegateAccess(input); },
  async startBreakGlass(input: StartBreakGlassInput) { await delay(); return iamRepository.startBreakGlass(input); },
  async endBreakGlass(input: EndBreakGlassInput) { await delay(); return iamRepository.endBreakGlass(input); },

  async search(query: string, tenantId?: string) { await delay(); return iamRepository.search(query, tenantId); },
  async exportData(format: 'csv' | 'pdf' | 'xlsx') { await delay(); return iamRepository.exportData(format); },
  async favorite(userId: string, entityType: 'user' | 'role' | 'policy' | 'session' | 'client', entityId: string) { await delay(); return iamRepository.favorite(userId, entityType, entityId); },
  async getFavorites(userId: string) { await delay(); return iamRepository.getFavorites(userId); },
  async share(input: ShareIamInput) { await delay(); return iamRepository.share(input); },
};
