import type { FinessRecord } from '@/services/directory/directory.types';

/** FINESS-style establishment records (France). */
export const FINESS_MOCK_RECORDS: FinessRecord[] = [
  {
    finessNumber: '750000001',
    legalName: 'AP-HP Hôpital Pitié-Salpêtrière',
    commercialName: 'Pitié-Salpêtrière',
    category: 'Centre hospitalier',
    department: 'Paris',
    city: 'Paris',
    postalCode: '75013',
    street: '47-83 Boulevard de l\'Hôpital',
    phone: '+33 1 42 16 00 00',
  },
  {
    finessNumber: '690000002',
    legalName: 'Hospices Civils de Lyon — Hôpital Édouard Herriot',
    commercialName: 'Hôpital Édouard Herriot',
    category: 'Centre hospitalier',
    department: 'Rhône',
    city: 'Lyon',
    postalCode: '69003',
    street: '5 Place d\'Arsonval',
    phone: '+33 4 72 11 73 33',
  },
  {
    finessNumber: '130000003',
    legalName: 'APHM Hôpital de la Timone',
    commercialName: 'Hôpital de la Timone',
    category: 'Centre hospitalier',
    department: 'Bouches-du-Rhône',
    city: 'Marseille',
    postalCode: '13005',
    street: '264 Rue Saint-Pierre',
    phone: '+33 4 91 38 00 00',
  },
  {
    finessNumber: '310000004',
    legalName: 'Clinique Pasteur',
    category: 'Clinique privée',
    department: 'Haute-Garonne',
    city: 'Toulouse',
    postalCode: '31076',
    street: '45 Avenue de Lombez',
    phone: '+33 5 61 47 00 00',
  },
  {
    finessNumber: '750000005',
    legalName: 'Pharmacie Centrale du Marais',
    category: 'Pharmacie d\'officine',
    department: 'Paris',
    city: 'Paris',
    postalCode: '75004',
    street: '12 Rue des Archives',
    phone: '+33 1 42 78 45 12',
  },
  {
    finessNumber: '690000006',
    legalName: 'Pharmacie Bellecour',
    category: 'Pharmacie d\'officine',
    department: 'Rhône',
    city: 'Lyon',
    postalCode: '69002',
    street: '8 Place Bellecour',
    phone: '+33 4 78 42 15 90',
  },
  {
    finessNumber: '750000007',
    legalName: 'SAMU de Paris — Transport Sanitaire',
    commercialName: 'SAMU 75',
    category: 'Transport sanitaire',
    department: 'Paris',
    city: 'Paris',
    postalCode: '75015',
    street: '1 Place du Panthéon',
    phone: '+33 1 45 68 80 00',
  },
  {
    finessNumber: '750000008',
    legalName: 'EHPAD Résidence Les Lilas',
    category: 'EHPAD',
    department: 'Paris',
    city: 'Paris',
    postalCode: '75020',
    street: '45 Rue des Lilas',
    phone: '+33 1 40 33 22 11',
  },
  {
    finessNumber: '920000009',
    legalName: 'Centre Médical La Défense',
    category: 'Centre de santé',
    department: 'Hauts-de-Seine',
    city: 'Puteaux',
    postalCode: '92800',
    street: '15 Parvis de la Défense',
    phone: '+33 1 47 75 60 00',
  },
  {
    finessNumber: '330000010',
    legalName: 'Clinique Tivoli',
    category: 'Clinique privée',
    department: 'Gironde',
    city: 'Bordeaux',
    postalCode: '33000',
    street: '2 Avenue de la République',
    phone: '+33 5 56 48 48 48',
  },
];
