import type {
  MedicationCategory,
  MedicationRecord,
} from '@/services/medical-library/medical-library.types';

type MedicationInput = Omit<MedicationRecord, 'available' | 'references'> &
  Partial<Pick<MedicationRecord, 'available' | 'references'>>;

function baseMedication(partial: MedicationInput): MedicationRecord {
  return {
    ...partial,
    available: partial.available ?? true,
    references: partial.references ?? [
      'BDPM — Base de Données Publique des Médicaments (mock)',
    ],
    relatedMedicationIds: partial.relatedMedicationIds ?? [],
    searchCount: partial.searchCount ?? 100,
    updatedAt: partial.updatedAt ?? new Date().toISOString(),
  };
}

export const MOCK_MEDICATIONS: MedicationRecord[] = [
  baseMedication({
    id: 'med-paracetamol',
    bdpmId: '60002283',
    name: 'Paracetamol',
    brandName: 'Doliprane',
    genericName: 'Paracetamol',
    strength: '500 mg',
    dosageForm: 'Tablet',
    route: 'oral',
    atcCode: 'N02BE01',
    therapeuticClass: 'Analgesics, non-opioid',
    category: 'pain_relief',
    manufacturer: 'Sanofi',
    prescriptionRequired: false,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 980,
    description:
      'Paracetamol is an analgesic and antipyretic used for mild to moderate pain and fever.',
    activeIngredients: ['Paracetamol 500 mg'],
    indications: [
      'Headache',
      'Fever',
      'Mild to moderate pain',
      'Post-vaccination fever',
    ],
    contraindications: [
      'Severe hepatic impairment',
      'Known hypersensitivity to paracetamol',
    ],
    warnings: [
      'Risk of hepatotoxicity with overdose',
      'Avoid alcohol during treatment',
    ],
    precautions: [
      'Monitor liver function in chronic use',
      'Check total daily dose from all sources',
    ],
    sideEffects: ['Rare: skin reactions', 'Overdose: liver damage'],
    administration: ['Take with water', 'Do not exceed recommended daily dose'],
    storage: 'Store below 25°C, protect from moisture.',
    patientInformation:
      'Do not exceed 3 g per day in adults without medical advice.',
    professionalInformation:
      'Maximum 4 g/day in adults; adjust in hepatic impairment.',
    dosages: [
      {
        population: 'adult',
        indication: 'Pain/fever',
        dose: '500–1000 mg',
        frequency: 'Every 4–6 hours',
        maxDose: '3 g/day',
      },
      {
        population: 'pediatric',
        indication: 'Fever',
        dose: '15 mg/kg',
        frequency: 'Every 6 hours',
        maxDose: '60 mg/kg/day',
      },
    ],
    interactions: [
      {
        drugName: 'Warfarin',
        severity: 'moderate',
        description: 'May enhance anticoagulant effect with prolonged use.',
      },
    ],
    relatedMedicationIds: ['med-ibuprofen', 'med-aspirin'],
    updatedAt: new Date().toISOString(),
  }),
  baseMedication({
    id: 'med-ibuprofen',
    bdpmId: '60498335',
    name: 'Ibuprofen',
    brandName: 'Advil',
    genericName: 'Ibuprofen',
    strength: '400 mg',
    dosageForm: 'Film-coated tablet',
    route: 'oral',
    atcCode: 'M01AE01',
    therapeuticClass: 'NSAIDs',
    category: 'pain_relief',
    manufacturer: 'Pfizer',
    prescriptionRequired: false,
    controlledSubstance: false,
    pregnancySafety: 'contraindicated',
    breastfeedingSafety: 'caution',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 720,
    description:
      'Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) for pain and inflammation.',
    activeIngredients: ['Ibuprofen 400 mg'],
    indications: ['Pain', 'Inflammation', 'Fever', 'Dysmenorrhea'],
    contraindications: [
      'Active peptic ulcer',
      'Third trimester pregnancy',
      'Severe heart failure',
    ],
    warnings: ['GI bleeding risk', 'Cardiovascular risk with long-term use'],
    precautions: ['Take with food', 'Avoid in renal impairment'],
    sideEffects: ['Dyspepsia', 'Nausea', 'Headache', 'Edema'],
    administration: ['Take after meals with water'],
    storage: 'Store below 30°C.',
    patientInformation: 'Shortest effective duration recommended.',
    professionalInformation: 'Consider gastroprotection in at-risk patients.',
    dosages: [
      {
        population: 'adult',
        indication: 'Pain',
        dose: '400 mg',
        frequency: 'Every 6–8 hours',
        maxDose: '1200 mg/day OTC',
      },
    ],
    interactions: [
      {
        drugName: 'Aspirin',
        severity: 'moderate',
        description: 'May reduce cardioprotective effect of aspirin.',
      },
      {
        drugName: 'ACE inhibitors',
        severity: 'moderate',
        description: 'May reduce antihypertensive efficacy.',
      },
    ],
    relatedMedicationIds: ['med-paracetamol'],
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  }),
  baseMedication({
    id: 'med-amoxicillin',
    bdpmId: '60315859',
    name: 'Amoxicillin',
    brandName: 'Clamoxyl',
    genericName: 'Amoxicillin',
    strength: '500 mg/5 ml',
    dosageForm: 'Oral suspension',
    route: 'oral',
    atcCode: 'J01CA04',
    therapeuticClass: 'Penicillin antibiotics',
    category: 'antibiotics',
    manufacturer: 'Laboratoire GlaxoSmithKline',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 650,
    description: 'Amoxicillin is a broad-spectrum aminopenicillin antibiotic.',
    activeIngredients: ['Amoxicillin trihydrate'],
    indications: [
      'Respiratory tract infections',
      'Otitis media',
      'Urinary tract infections',
    ],
    contraindications: [
      'Penicillin allergy',
      'History of amoxicillin-associated cholestatic jaundice',
    ],
    warnings: [
      'Complete full course',
      'Risk of Clostridioides difficile infection',
    ],
    precautions: ['Adjust dose in renal impairment', 'Assess allergy history'],
    sideEffects: ['Diarrhea', 'Nausea', 'Skin rash', 'Candidiasis'],
    administration: ['Shake suspension well', 'Can take with or without food'],
    storage: 'Refrigerate suspension after reconstitution; use within 7 days.',
    patientInformation: 'Finish all prescribed doses even if feeling better.',
    professionalInformation:
      'First-line for many community-acquired infections per local guidelines.',
    dosages: [
      {
        population: 'adult',
        indication: 'Infection',
        dose: '500 mg',
        frequency: 'Every 8 hours',
      },
      {
        population: 'pediatric',
        indication: 'Otitis media',
        dose: '25 mg/kg',
        frequency: 'Every 12 hours',
      },
    ],
    interactions: [
      {
        drugName: 'Methotrexate',
        severity: 'major',
        description: 'May increase methotrexate toxicity.',
      },
    ],
    relatedMedicationIds: [],
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  }),
  baseMedication({
    id: 'med-metformin',
    bdpmId: '65197451',
    name: 'Metformin',
    brandName: 'Glucophage',
    genericName: 'Metformin hydrochloride',
    strength: '850 mg',
    dosageForm: 'Film-coated tablet',
    route: 'oral',
    atcCode: 'A10BA02',
    therapeuticClass: 'Biguanides',
    category: 'diabetes',
    manufacturer: 'Merck',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'caution',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 890,
    description:
      'Metformin is a first-line oral antidiabetic for type 2 diabetes mellitus.',
    activeIngredients: ['Metformin hydrochloride 850 mg'],
    indications: [
      'Type 2 diabetes mellitus',
      'Polycystic ovary syndrome (off-label)',
    ],
    contraindications: [
      'eGFR < 30',
      'Acute metabolic acidosis',
      'Severe dehydration',
    ],
    warnings: [
      'Lactic acidosis risk',
      'Withhold before iodinated contrast procedures',
    ],
    precautions: [
      'Monitor renal function',
      'B12 deficiency with long-term use',
    ],
    sideEffects: ['GI upset', 'Diarrhea', 'Metallic taste', 'B12 deficiency'],
    administration: ['Take with meals to reduce GI effects'],
    storage: 'Store below 25°C.',
    patientInformation:
      'Report muscle pain, breathing difficulty, or unusual fatigue.',
    professionalInformation:
      'Start low and titrate; consider extended-release formulation if GI intolerance.',
    dosages: [
      {
        population: 'adult',
        indication: 'Type 2 diabetes',
        dose: '850 mg',
        frequency: 'Twice daily',
        maxDose: '2550 mg/day',
      },
      {
        population: 'geriatric',
        indication: 'Type 2 diabetes',
        dose: '500 mg',
        frequency: 'Once daily',
        notes: 'Titrate cautiously',
      },
    ],
    interactions: [
      {
        drugName: 'Iodinated contrast media',
        severity: 'major',
        description: 'Withhold metformin around contrast administration.',
      },
    ],
    relatedMedicationIds: ['med-insulin'],
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  }),
  baseMedication({
    id: 'med-insulin',
    bdpmId: '63256759',
    name: 'Insulin Glargine',
    brandName: 'Lantus',
    genericName: 'Insulin glargine',
    strength: '100 IU/ml',
    dosageForm: 'Injectable solution',
    route: 'injection',
    atcCode: 'A10AE04',
    therapeuticClass: 'Long-acting insulins',
    category: 'diabetes',
    manufacturer: 'Sanofi',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 540,
    description: 'Insulin glargine is a long-acting basal insulin analogue.',
    activeIngredients: ['Insulin glargine 100 IU/ml'],
    indications: ['Type 1 diabetes', 'Type 2 diabetes requiring basal insulin'],
    contraindications: ['Hypoglycemia', 'Hypersensitivity to insulin glargine'],
    warnings: ['Never share pens', 'Rotate injection sites'],
    precautions: [
      'Monitor blood glucose',
      'Adjust dose with illness or exercise changes',
    ],
    sideEffects: [
      'Hypoglycemia',
      'Injection site reactions',
      'Weight gain',
      'Lipodystrophy',
    ],
    administration: [
      'Subcutaneous once daily at same time',
      'Do not mix with other insulins in same syringe',
    ],
    storage: 'Unopened: refrigerate. In use: room temperature up to 28 days.',
    patientInformation:
      'Recognize hypoglycemia symptoms and keep fast-acting sugar available.',
    professionalInformation:
      'Individualize dose; consider 20% reduction when converting from NPH.',
    dosages: [
      {
        population: 'adult',
        indication: 'Basal insulin',
        dose: '0.1–0.2 units/kg',
        frequency: 'Once daily',
      },
    ],
    interactions: [
      {
        drugName: 'Beta-blockers',
        severity: 'moderate',
        description: 'May mask hypoglycemia symptoms.',
      },
    ],
    relatedMedicationIds: ['med-metformin'],
    updatedAt: new Date(Date.now() - 345600000).toISOString(),
  }),
  baseMedication({
    id: 'med-salbutamol',
    bdpmId: '64405985',
    name: 'Salbutamol',
    brandName: 'Ventoline',
    genericName: 'Salbutamol sulfate',
    strength: '100 mcg/dose',
    dosageForm: 'Pressurized inhalation',
    route: 'inhalation',
    atcCode: 'R03AC02',
    therapeuticClass: 'Selective beta-2 agonists',
    category: 'respiratory',
    manufacturer: 'GSK',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 610,
    description:
      'Salbutamol is a short-acting bronchodilator for asthma and COPD relief.',
    activeIngredients: ['Salbutamol sulfate 100 mcg per actuation'],
    indications: [
      'Asthma relief',
      'COPD bronchospasm',
      'Exercise-induced bronchospasm',
    ],
    contraindications: ['Hypersensitivity to salbutamol'],
    warnings: [
      'Paradoxical bronchospasm',
      'Not for regular control monotherapy in asthma',
    ],
    precautions: [
      'Monitor heart rate',
      'Use spacer in children if appropriate',
    ],
    sideEffects: [
      'Tremor',
      'Tachycardia',
      'Headache',
      'Hypokalemia at high doses',
    ],
    administration: [
      'Shake inhaler',
      'Rinse mouth after use if corticosteroid co-therapy',
    ],
    storage: 'Store below 25°C; do not puncture canister.',
    patientInformation:
      'Seek help if rescue inhaler needed more than twice weekly.',
    professionalInformation: 'Assess inhaler technique at each visit.',
    dosages: [
      {
        population: 'adult',
        indication: 'Acute bronchospasm',
        dose: '1–2 puffs',
        frequency: 'As needed',
        maxDose: '8 puffs/day typical',
      },
      {
        population: 'pediatric',
        indication: 'Asthma relief',
        dose: '1 puff',
        frequency: 'As needed',
      },
    ],
    interactions: [],
    relatedMedicationIds: [],
    updatedAt: new Date(Date.now() - 432000000).toISOString(),
  }),
  baseMedication({
    id: 'med-levothyroxine',
    bdpmId: '60477288',
    name: 'Levothyroxine',
    brandName: 'Levothyrox',
    genericName: 'Levothyroxine sodium',
    strength: '100 mcg',
    dosageForm: 'Scored tablet',
    route: 'oral',
    atcCode: 'H03AA01',
    therapeuticClass: 'Thyroid hormones',
    category: 'endocrinology',
    manufacturer: 'Merck',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'safe',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 780,
    description:
      'Levothyroxine is synthetic T4 for hypothyroidism and thyroid hormone replacement.',
    activeIngredients: ['Levothyroxine sodium 100 mcg'],
    indications: [
      'Hypothyroidism',
      'Thyroid suppression therapy',
      'Congenital hypothyroidism',
    ],
    contraindications: [
      'Untreated adrenal insufficiency',
      'Acute myocardial infarction with uncorrected hypothyroidism',
    ],
    warnings: ['Do not use for weight loss', 'Tachycardia with overdose'],
    precautions: [
      'Take on empty stomach',
      'Separate from calcium/iron by 4 hours',
    ],
    sideEffects: ['Palpitations', 'Weight loss', 'Insomnia if over-replaced'],
    administration: ['Take 30–60 minutes before breakfast with water'],
    storage: 'Store below 25°C, protect from light.',
    patientInformation: 'Take consistently at the same time daily.',
    professionalInformation: 'Recheck TSH 6–8 weeks after dose change.',
    dosages: [
      {
        population: 'adult',
        indication: 'Hypothyroidism',
        dose: '1.6 mcg/kg',
        frequency: 'Once daily',
      },
      {
        population: 'geriatric',
        indication: 'Hypothyroidism',
        dose: '12.5–25 mcg',
        frequency: 'Once daily',
        notes: 'Start low',
      },
    ],
    interactions: [
      {
        drugName: 'Calcium supplements',
        severity: 'moderate',
        description: 'Reduce absorption; separate administration.',
      },
    ],
    relatedMedicationIds: [],
    updatedAt: new Date(Date.now() - 518400000).toISOString(),
  }),
  baseMedication({
    id: 'med-omeprazole',
    bdpmId: '60234100',
    name: 'Omeprazole',
    brandName: 'Mopral',
    genericName: 'Omeprazole',
    strength: '20 mg',
    dosageForm: 'Gastro-resistant capsule',
    route: 'oral',
    atcCode: 'A02BC01',
    therapeuticClass: 'Proton pump inhibitors',
    category: 'gastroenterology',
    manufacturer: 'AstraZeneca',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'caution',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 670,
    description:
      'Omeprazole reduces gastric acid secretion for GERD and peptic ulcer disease.',
    activeIngredients: ['Omeprazole 20 mg'],
    indications: [
      'GERD',
      'Peptic ulcer',
      'H. pylori eradication (combination)',
      'NSAID gastroprotection',
    ],
    contraindications: ['Hypersensitivity to omeprazole or benzimidazoles'],
    warnings: [
      'Long-term use: monitor magnesium, B12',
      'Increased fracture risk',
    ],
    precautions: [
      'Review need for long-term therapy',
      'May mask gastric cancer symptoms',
    ],
    sideEffects: ['Headache', 'Diarrhea', 'Abdominal pain', 'Nausea'],
    administration: [
      'Swallow whole before breakfast',
      'Do not crush gastro-resistant capsules',
    ],
    storage: 'Store below 25°C.',
    patientInformation: 'Report persistent GI symptoms to clinician.',
    professionalInformation:
      'Consider step-down after healing phase when appropriate.',
    dosages: [
      {
        population: 'adult',
        indication: 'GERD',
        dose: '20 mg',
        frequency: 'Once daily',
        maxDose: '40 mg/day',
      },
    ],
    interactions: [
      {
        drugName: 'Clopidogrel',
        severity: 'moderate',
        description: 'May reduce antiplatelet effect of clopidogrel.',
      },
    ],
    relatedMedicationIds: [],
    updatedAt: new Date(Date.now() - 604800000).toISOString(),
  }),
  baseMedication({
    id: 'med-amlodipine',
    bdpmId: '63415964',
    name: 'Amlodipine',
    brandName: 'Amlodipine EG',
    genericName: 'Amlodipine besylate',
    strength: '5 mg',
    dosageForm: 'Tablet',
    route: 'oral',
    atcCode: 'C08CA01',
    therapeuticClass: 'Dihydropyridine calcium channel blockers',
    category: 'cardiology',
    manufacturer: 'EG Labo',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'caution',
    pediatricApproved: false,
    geriatricApproved: true,
    searchCount: 560,
    description:
      'Amlodipine is a long-acting calcium channel blocker for hypertension and angina.',
    activeIngredients: ['Amlodipine besylate 5 mg'],
    indications: [
      'Hypertension',
      'Chronic stable angina',
      'Vasospastic angina',
    ],
    contraindications: [
      'Severe hypotension',
      'Shock',
      'Unstable angina (except Prinzmetal)',
    ],
    warnings: [
      'Peripheral edema',
      'Worsening angina on initiation in rare cases',
    ],
    precautions: [
      'Use cautiously in severe aortic stenosis',
      'Hepatic impairment dose adjustment',
    ],
    sideEffects: ['Edema', 'Flushing', 'Palpitations', 'Dizziness'],
    administration: ['Once daily, with or without food'],
    storage: 'Store below 30°C.',
    patientInformation: 'Rise slowly from sitting to reduce dizziness.',
    professionalInformation:
      'Combine with ACE inhibitor in most hypertensive patients per guidelines.',
    dosages: [
      {
        population: 'adult',
        indication: 'Hypertension',
        dose: '5 mg',
        frequency: 'Once daily',
        maxDose: '10 mg/day',
      },
      {
        population: 'geriatric',
        indication: 'Hypertension',
        dose: '2.5 mg',
        frequency: 'Once daily',
      },
    ],
    interactions: [
      {
        drugName: 'Simvastatin',
        severity: 'moderate',
        description: 'Limit simvastatin dose to 20 mg with amlodipine.',
      },
    ],
    relatedMedicationIds: ['med-atorvastatin'],
    updatedAt: new Date(Date.now() - 691200000).toISOString(),
  }),
  baseMedication({
    id: 'med-atorvastatin',
    bdpmId: '63431654',
    name: 'Atorvastatin',
    brandName: 'Tahor',
    genericName: 'Atorvastatin calcium',
    strength: '20 mg',
    dosageForm: 'Film-coated tablet',
    route: 'oral',
    atcCode: 'C10AA05',
    therapeuticClass: 'HMG-CoA reductase inhibitors',
    category: 'cardiology',
    manufacturer: 'Pfizer',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'contraindicated',
    breastfeedingSafety: 'contraindicated',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 820,
    description:
      'Atorvastatin lowers LDL cholesterol and reduces cardiovascular risk.',
    activeIngredients: ['Atorvastatin calcium 20 mg'],
    indications: [
      'Hyperlipidemia',
      'Primary prevention of CV events',
      'Secondary prevention post-MI',
    ],
    contraindications: ['Active liver disease', 'Pregnancy', 'Breastfeeding'],
    warnings: ['Myopathy/rhabdomyolysis risk', 'Monitor LFTs'],
    precautions: [
      'Avoid grapefruit juice in large quantities',
      'Counsel on muscle pain reporting',
    ],
    sideEffects: ['Myalgia', 'Headache', 'Elevated transaminases', 'GI upset'],
    administration: ['Once daily, any time of day'],
    storage: 'Store below 25°C.',
    patientInformation:
      'Report unexplained muscle pain, tenderness, or weakness.',
    professionalInformation:
      'Check lipid panel 4–12 weeks after initiation or dose change.',
    dosages: [
      {
        population: 'adult',
        indication: 'Hyperlipidemia',
        dose: '10–20 mg',
        frequency: 'Once daily',
        maxDose: '80 mg/day',
      },
    ],
    interactions: [
      {
        drugName: 'Clarithromycin',
        severity: 'major',
        description: 'Increased statin exposure; myopathy risk.',
      },
    ],
    relatedMedicationIds: ['med-amlodipine', 'med-clopidogrel'],
    updatedAt: new Date(Date.now() - 777600000).toISOString(),
  }),
  baseMedication({
    id: 'med-aspirin',
    bdpmId: '60002746',
    name: 'Aspirin',
    brandName: 'Aspegic',
    genericName: 'Acetylsalicylic acid',
    strength: '1000 mg',
    dosageForm: 'Oral powder sachet',
    route: 'oral',
    atcCode: 'N02BA01',
    therapeuticClass: 'Salicylic acid derivatives',
    category: 'pain_relief',
    manufacturer: 'Bayer',
    prescriptionRequired: false,
    controlledSubstance: false,
    pregnancySafety: 'contraindicated',
    breastfeedingSafety: 'caution',
    pediatricApproved: false,
    geriatricApproved: true,
    searchCount: 700,
    description:
      'Aspirin is an analgesic, antipyretic, and antiplatelet agent at low doses.',
    activeIngredients: ['Acetylsalicylic acid'],
    indications: [
      'Pain',
      'Fever',
      'Secondary prevention of cardiovascular events (low dose)',
    ],
    contraindications: [
      'Children with viral illness (Reye syndrome)',
      'Active bleeding',
      'Peptic ulcer',
    ],
    warnings: ['Bleeding risk', 'Avoid in last trimester of pregnancy'],
    precautions: [
      'Discontinue before elective surgery',
      'Asthma sensitivity in some patients',
    ],
    sideEffects: ['GI irritation', 'Bleeding', 'Tinnitus at high doses'],
    administration: [
      'Dissolve sachet in water',
      'Low-dose forms used for antiplatelet therapy',
    ],
    storage: 'Store in dry place below 25°C.',
    patientInformation:
      'Low-dose aspirin for heart protection requires medical supervision.',
    professionalInformation:
      'Balance bleeding vs thrombotic risk for primary prevention.',
    dosages: [
      {
        population: 'adult',
        indication: 'Pain',
        dose: '500–1000 mg',
        frequency: 'Every 4–6 hours',
      },
      {
        population: 'adult',
        indication: 'Antiplatelet',
        dose: '75–100 mg',
        frequency: 'Once daily',
      },
    ],
    interactions: [
      {
        drugName: 'Ibuprofen',
        severity: 'moderate',
        description:
          'Ibuprofen may interfere with aspirin antiplatelet effect.',
      },
      {
        drugName: 'Warfarin',
        severity: 'major',
        description: 'Increased bleeding risk.',
      },
    ],
    relatedMedicationIds: ['med-clopidogrel', 'med-ibuprofen'],
    updatedAt: new Date(Date.now() - 864000000).toISOString(),
  }),
  baseMedication({
    id: 'med-clopidogrel',
    bdpmId: '63406493',
    name: 'Clopidogrel',
    brandName: 'Plavix',
    genericName: 'Clopidogrel bisulfate',
    strength: '75 mg',
    dosageForm: 'Film-coated tablet',
    route: 'oral',
    atcCode: 'B01AC04',
    therapeuticClass: 'Platelet aggregation inhibitors',
    category: 'cardiology',
    manufacturer: 'Sanofi',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'unknown',
    pediatricApproved: false,
    geriatricApproved: true,
    searchCount: 590,
    description:
      'Clopidogrel inhibits platelet aggregation for ACS and post-stent therapy.',
    activeIngredients: ['Clopidogrel bisulfate 75 mg'],
    indications: [
      'Acute coronary syndrome',
      'Recent MI, stroke, or PAD',
      'Post-coronary stent',
    ],
    contraindications: [
      'Active pathological bleeding',
      'Severe hepatic impairment',
    ],
    warnings: ['Bleeding risk', 'TTP reported rarely'],
    precautions: [
      'Stop 5 days before major surgery if feasible',
      'CYP2C19 poor metabolizers may have reduced effect',
    ],
    sideEffects: ['Bleeding', 'Diarrhea', 'Dyspepsia', 'Rash'],
    administration: ['Once daily with or without food'],
    storage: 'Store below 30°C.',
    patientInformation: 'Report blood in stool, urine, or unusual bruising.',
    professionalInformation:
      'Consider prasugrel or ticagrelor per ACS guidelines when indicated.',
    dosages: [
      {
        population: 'adult',
        indication: 'Maintenance antiplatelet',
        dose: '75 mg',
        frequency: 'Once daily',
      },
    ],
    interactions: [
      {
        drugName: 'Omeprazole',
        severity: 'moderate',
        description: 'May reduce antiplatelet effect via CYP2C19.',
      },
      {
        drugName: 'Aspirin',
        severity: 'moderate',
        description:
          'Dual therapy increases bleeding risk but often indicated post-ACS.',
      },
    ],
    relatedMedicationIds: ['med-aspirin', 'med-atorvastatin'],
    updatedAt: new Date(Date.now() - 950400000).toISOString(),
  }),
  baseMedication({
    id: 'med-spikevax',
    bdpmId: '65996239',
    name: 'Spikevax (COVID-19 Vaccine)',
    brandName: 'Spikevax',
    genericName: 'COVID-19 mRNA vaccine',
    strength: '50 mcg/0.5 ml',
    dosageForm: 'Injectable suspension',
    route: 'injection',
    atcCode: 'J07BX03',
    therapeuticClass: 'COVID-19 vaccines',
    category: 'vaccines',
    manufacturer: 'Moderna',
    prescriptionRequired: true,
    controlledSubstance: false,
    pregnancySafety: 'caution',
    breastfeedingSafety: 'safe',
    pediatricApproved: true,
    geriatricApproved: true,
    searchCount: 430,
    description: 'mRNA vaccine for active immunization against SARS-CoV-2.',
    activeIngredients: ['Nucleoside-modified mRNA encoding spike protein'],
    indications: ['Prevention of COVID-19'],
    contraindications: [
      'Severe allergic reaction to previous dose or component',
    ],
    warnings: [
      'Observe 15 minutes post-vaccination',
      'Myocarditis/pericarditis rare risk in young males',
    ],
    precautions: ['Immunocompromised may have reduced response'],
    sideEffects: [
      'Injection site pain',
      'Fatigue',
      'Headache',
      'Myalgia',
      'Fever',
    ],
    administration: [
      'Intramuscular deltoid',
      'Follow national immunization schedule',
    ],
    storage:
      'Ultra-cold chain until thaw; use within approved window after preparation.',
    patientInformation: 'Common side effects resolve within a few days.',
    professionalInformation:
      'Document lot number and administration site per pharmacovigilance requirements.',
    dosages: [
      {
        population: 'adult',
        indication: 'Primary series/booster',
        dose: '0.5 ml',
        frequency: 'Per national schedule',
      },
      {
        population: 'pediatric',
        indication: 'Pediatric dose',
        dose: '0.25 ml',
        frequency: 'Per national schedule',
      },
    ],
    interactions: [],
    relatedMedicationIds: [],
    updatedAt: new Date(Date.now() - 1036800000).toISOString(),
  }),
];

export const POPULAR_MEDICATIONS = [
  'Paracetamol',
  'Metformin',
  'Atorvastatin',
  'Amoxicillin',
  'Ibuprofen',
  'Omeprazole',
];

export const RECENT_MEDICATION_SEARCHES_KEY =
  'medease:medical-library:recent-searches';

export function getCategoryCounts(): Record<MedicationCategory, number> {
  const counts = {} as Record<MedicationCategory, number>;
  for (const med of MOCK_MEDICATIONS) {
    counts[med.category] = (counts[med.category] ?? 0) + 1;
  }
  return counts;
}
