import type { SeedModule } from '../types';

const DEMO_TENANT_ID = '01930000-0000-7000-8000-000000000001';
const DEMO_ADMIN_ID = '01930000-0000-7000-8000-000000000101';

const FAC_PARIS = '01930000-0000-7000-8000-000000000201';
const FAC_LYON = '01930000-0000-7000-8000-000000000202';
const FAC_TOUR = '01930000-0000-7000-8000-000000000203';
const PRO_MARTIN = '01930000-0000-7000-8000-000000000501';
const PRO_BERNARD = '01930000-0000-7000-8000-000000000502';
const PRO_DUPONT = '01930000-0000-7000-8000-000000000503';
const PHARM = '01930000-0000-7000-8000-000000000701';
const TRANSPORT = '01930000-0000-7000-8000-000000000801';

const MED = {
  para: '01930000-0000-7000-8000-000000000e01',
  ibu: '01930000-0000-7000-8000-000000000e02',
  amox: '01930000-0000-7000-8000-000000000e03',
  met: '01930000-0000-7000-8000-000000000e04',
  ins: '01930000-0000-7000-8000-000000000e05',
  salb: '01930000-0000-7000-8000-000000000e06',
  omep: '01930000-0000-7000-8000-000000000e07',
  ator: '01930000-0000-7000-8000-000000000e08',
} as const;

export const directoryMedicalLibrarySeed: SeedModule = {
  name: 'directory-medical-library',
  async run(ctx) {
    if (ctx.dryRun) return;

    const { PrismaClient, runInSystemTransaction } =
      await import('@medease/prisma');
    type TransactionClient = Parameters<
      Parameters<typeof runInSystemTransaction>[1]
    >[0];
    const prisma = new PrismaClient();

    try {
      await runInSystemTransaction(prisma, async (tx: TransactionClient) => {
        const providers = [
          {
            id: PRO_DUPONT,
            type: 'professional' as const,
            name: 'Dr. Marie Dupont',
            title: 'Médecin généraliste',
            specialty: 'Médecine générale',
            medicalSpecialty: 'Médecine générale',
            street: '22 Rue de Rivoli',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75004',
            phone: '+33 1 42 77 88 99',
            distanceKm: 0.8,
            latitude: 48.8556,
            longitude: 2.3609,
            availability: 'Disponible aujourd’hui',
            teleconsultation: true,
            associatedFacilityIds: [FAC_PARIS],
          },
          {
            id: PRO_MARTIN,
            type: 'professional' as const,
            name: 'Dr. Jean-Luc Martin',
            title: 'Cardiologue',
            specialty: 'Cardiologie',
            medicalSpecialty: 'Cardiologie',
            street: "47 Boulevard de l'Hôpital",
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 42 16 00 10',
            distanceKm: 1.2,
            latitude: 48.8372,
            longitude: 2.3628,
            availability: 'Ouvert maintenant',
            teleconsultation: true,
            associatedFacilityIds: [FAC_PARIS],
          },
          {
            id: PRO_BERNARD,
            type: 'professional' as const,
            name: 'Dr. Sophie Bernard',
            title: 'Endocrinologue',
            specialty: 'Endocrinologie',
            medicalSpecialty: 'Endocrinologie',
            street: 'Place d’Arsonval',
            city: 'Lyon',
            department: 'Rhône',
            postalCode: '69003',
            phone: '+33 4 72 11 70 00',
            distanceKm: 5.4,
            latitude: 45.742,
            longitude: 4.879,
            availability: 'Disponible aujourd’hui',
            teleconsultation: false,
            associatedFacilityIds: [FAC_LYON],
          },
          {
            id: FAC_PARIS,
            type: 'facility' as const,
            name: 'Pitié-Salpêtrière',
            facilityType: 'Centre hospitalier',
            finessNumber: '750000001',
            street: "47-83 Boulevard de l'Hôpital",
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 42 16 00 00',
            distanceKm: 1.1,
            latitude: 48.8375,
            longitude: 2.3631,
            availability: 'Ouvert maintenant',
            emergencyServices: true,
            services: ['Urgences', 'Imagerie', 'Laboratoire', 'Consultations'],
          },
          {
            id: FAC_LYON,
            type: 'facility' as const,
            name: 'Édouard Herriot',
            facilityType: 'Centre hospitalier',
            finessNumber: '690000001',
            street: '5 Place d’Arsonval',
            city: 'Lyon',
            department: 'Rhône',
            postalCode: '69003',
            phone: '+33 4 72 11 70 00',
            distanceKm: 5.0,
            latitude: 45.7435,
            longitude: 4.881,
            availability: 'Ouvert maintenant',
            emergencyServices: true,
            services: ['Urgences', 'Chirurgie', 'Consultations'],
          },
          {
            id: FAC_TOUR,
            type: 'facility' as const,
            name: 'CHU de Tours',
            facilityType: 'Centre hospitalier universitaire',
            finessNumber: '370000001',
            street: '2 Boulevard Tonnellé',
            city: 'Tours',
            department: 'Indre-et-Loire',
            postalCode: '37000',
            phone: '+33 2 47 47 47 47',
            distanceKm: 12.0,
            latitude: 47.389,
            longitude: 0.6805,
            availability: 'Ouvert maintenant',
            emergencyServices: true,
            services: ['Urgences', 'Maternité', 'Consultations'],
          },
          {
            id: PHARM,
            type: 'pharmacy' as const,
            name: 'Pharmacie du Marais',
            facilityType: 'Officine',
            street: '12 Rue des Archives',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75004',
            phone: '+33 1 42 72 11 22',
            distanceKm: 0.5,
            latitude: 48.8595,
            longitude: 2.3612,
            availability: 'Ouvert maintenant',
            services: ['Dispensation', 'Vaccination', 'Conseils'],
          },
          {
            id: TRANSPORT,
            type: 'transport' as const,
            name: 'MedEase Ambulance Paris',
            facilityType: 'Transport sanitaire',
            street: '8 Rue de Tolbiac',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 44 00 00 00',
            distanceKm: 2.0,
            latitude: 48.827,
            longitude: 2.358,
            availability: 'Dispatch 24/7',
            emergencyServices: true,
            services: ['VSL', 'Ambulance', 'Transfert inter-hospitalier'],
          },
        ];

        for (const p of providers) {
          await tx.directoryProvider.upsert({
            where: { id: p.id },
            create: {
              id: p.id,
              tenantId: DEMO_TENANT_ID,
              type: p.type,
              name: p.name,
              title: 'title' in p ? p.title : undefined,
              specialty: 'specialty' in p ? p.specialty : undefined,
              medicalSpecialty:
                'medicalSpecialty' in p ? p.medicalSpecialty : undefined,
              facilityType: 'facilityType' in p ? p.facilityType : undefined,
              finessNumber: 'finessNumber' in p ? p.finessNumber : undefined,
              street: p.street,
              city: p.city,
              department: p.department,
              postalCode: p.postalCode,
              country: 'France',
              distanceKm: p.distanceKm,
              latitude: 'latitude' in p ? p.latitude : undefined,
              longitude: 'longitude' in p ? p.longitude : undefined,
              phone: p.phone,
              availability: p.availability,
              status: 'stable',
              languages: ['French'],
              services: 'services' in p && p.services ? p.services : [],
              teleconsultation:
                'teleconsultation' in p ? Boolean(p.teleconsultation) : false,
              emergencyServices:
                'emergencyServices' in p ? Boolean(p.emergencyServices) : false,
              associatedFacilityIds:
                'associatedFacilityIds' in p && p.associatedFacilityIds
                  ? p.associatedFacilityIds
                  : [],
              createdBy: DEMO_ADMIN_ID,
            },
            update: {
              name: p.name,
              title: 'title' in p ? p.title : undefined,
              specialty: 'specialty' in p ? p.specialty : undefined,
              medicalSpecialty:
                'medicalSpecialty' in p ? p.medicalSpecialty : undefined,
              facilityType: 'facilityType' in p ? p.facilityType : undefined,
              phone: p.phone,
              availability: p.availability,
              distanceKm: p.distanceKm,
              latitude: 'latitude' in p ? p.latitude : undefined,
              longitude: 'longitude' in p ? p.longitude : undefined,
              services: 'services' in p && p.services ? p.services : [],
              teleconsultation:
                'teleconsultation' in p ? Boolean(p.teleconsultation) : false,
              emergencyServices:
                'emergencyServices' in p ? Boolean(p.emergencyServices) : false,
              associatedFacilityIds:
                'associatedFacilityIds' in p && p.associatedFacilityIds
                  ? p.associatedFacilityIds
                  : [],
              languages: ['Français'],
              active: true,
              updatedBy: DEMO_ADMIN_ID,
            },
          });
        }

        const meds = [
          {
            id: MED.para,
            bdpmId: '60002283',
            name: 'Paracétamol',
            brandName: 'Doliprane',
            genericName: 'Paracétamol',
            strength: '500 mg',
            dosageForm: 'Comprimé',
            route: 'oral',
            atcCode: 'N02BE01',
            therapeuticClass: 'Antalgiques non opioïdes',
            category: 'pain_relief',
            manufacturer: 'Sanofi',
            prescriptionRequired: false,
            pregnancySafety: 'caution',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 980,
            description:
              'Antalgique et antipyrétique pour les douleurs légères à modérées et la fièvre.',
            indications: [
              'Douleurs légères à modérées',
              'Fièvre',
              'Céphalées',
            ],
            contraindications: [
              'Hypersensibilité au paracétamol',
              'Insuffisance hépatique sévère',
            ],
            warnings: [
              'Ne pas dépasser 3 g/jour chez l’adulte',
              'Risque d’hépatotoxicité en cas de surdosage',
            ],
            sideEffects: ['Rare : réactions cutanées', 'Troubles hépatiques en surdosage'],
            dosages: [
              {
                population: 'adult',
                indication: 'Douleur / fièvre',
                dose: '500 mg à 1 g',
                frequency: 'toutes les 6 à 8 h (max 3 g/j)',
              },
              {
                population: 'pediatric',
                indication: 'Douleur / fièvre',
                dose: '15 mg/kg',
                frequency: 'toutes les 6 h',
              },
            ],
            patientInformation:
              'Respectez la posologie. En cas de douleur persistante, consultez un médecin.',
            professionalInformation:
              'Inhibiteur faible de la COX. Métabolisme hépatique. Antidote : N-acétylcystéine.',
            related: [MED.ibu],
          },
          {
            id: MED.ibu,
            bdpmId: '60004121',
            name: 'Ibuprofène',
            brandName: 'Advil',
            genericName: 'Ibuprofène',
            strength: '400 mg',
            dosageForm: 'Comprimé',
            route: 'oral',
            atcCode: 'M01AE01',
            therapeuticClass: 'AINS',
            category: 'pain_relief',
            manufacturer: 'Pfizer',
            prescriptionRequired: false,
            pregnancySafety: 'contraindicated',
            breastfeedingSafety: 'caution',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 760,
            description:
              'Anti-inflammatoire non stéroïdien pour douleur, inflammation et fièvre.',
            indications: ['Douleur', 'Inflammation', 'Fièvre', 'Dysménorrhée'],
            contraindications: [
              'Ulcère gastroduodénal évolutif',
              '3e trimestre de grossesse',
              'Insuffisance rénale sévère',
            ],
            warnings: [
              'Risque digestif et cardiovasculaire',
              'À prendre au cours d’un repas',
            ],
            sideEffects: ['Nausées', 'Douleurs gastriques', 'Céphalées'],
            dosages: [
              {
                population: 'adult',
                indication: 'Douleur / inflammation',
                dose: '200–400 mg',
                frequency: '3 fois/jour (max 1200 mg/j OTC)',
              },
            ],
            patientInformation:
              'Ne pas utiliser en fin de grossesse. Signalez tout saignement digestif.',
            professionalInformation:
              'Inhibiteur COX non sélectif. Interactions avec anticoagulants et IEC.',
            related: [MED.para],
          },
          {
            id: MED.amox,
            bdpmId: '60001990',
            name: 'Amoxicilline',
            brandName: 'Clamoxyl',
            genericName: 'Amoxicilline',
            strength: '1 g',
            dosageForm: 'Gélule',
            route: 'oral',
            atcCode: 'J01CA04',
            therapeuticClass: 'Pénicillines',
            category: 'antibiotics',
            manufacturer: 'GSK',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 640,
            description: 'Antibiotique pénicilline à large spectre.',
            indications: [
              'Infections ORL',
              'Infections urinaires',
              'Infections respiratoires',
            ],
            contraindications: ['Allergie aux pénicillines'],
            warnings: [
              'Terminer le traitement prescrit',
              'Surveiller réactions allergiques',
            ],
            sideEffects: ['Diarrhée', 'Nausées', 'Éruptions cutanées'],
            dosages: [
              {
                population: 'adult',
                indication: 'Infection bactérienne',
                dose: '1 g',
                frequency: '2 à 3 fois/jour',
              },
            ],
            patientInformation:
              'Prenez le traitement jusqu’au bout même si vous vous sentez mieux.',
            professionalInformation:
              'Bactéricide. Adapter à la fonction rénale. Résistance possible.',
            related: [] as string[],
          },
          {
            id: MED.met,
            bdpmId: '60005512',
            name: 'Metformine',
            brandName: 'Glucophage',
            genericName: 'Metformine',
            strength: '850 mg',
            dosageForm: 'Comprimé',
            route: 'oral',
            atcCode: 'A10BA02',
            therapeuticClass: 'Biguanides',
            category: 'diabetes',
            manufacturer: 'Merck',
            prescriptionRequired: true,
            pregnancySafety: 'caution',
            breastfeedingSafety: 'caution',
            pediatricApproved: false,
            geriatricApproved: true,
            searchCount: 820,
            description:
              'Antidiabétique oral de première intention dans le diabète de type 2.',
            indications: ['Diabète de type 2'],
            contraindications: [
              'Acidose lactique',
              'Insuffisance rénale sévère',
              'Insuffisance hépatique',
            ],
            warnings: [
              'Arrêt temporaire avant examens au produit de contraste',
              'Surveiller la fonction rénale',
            ],
            sideEffects: ['Troubles digestifs', 'Goût métallique'],
            dosages: [
              {
                population: 'adult',
                indication: 'Diabète type 2',
                dose: '850 mg',
                frequency: '1 à 2 fois/jour au repas',
              },
            ],
            patientInformation:
              'Prenez pendant les repas pour limiter les effets digestifs.',
            professionalInformation:
              'Réduit la production hépatique de glucose. Risque d’acidose lactique rare.',
            related: [MED.ins],
          },
          {
            id: MED.ins,
            bdpmId: '60006601',
            name: 'Insuline glargine',
            brandName: 'Lantus',
            genericName: 'Insuline glargine',
            strength: '100 UI/mL',
            dosageForm: 'Injection',
            route: 'injection',
            atcCode: 'A10AE04',
            therapeuticClass: 'Insuline basale longue durée',
            category: 'diabetes',
            manufacturer: 'Sanofi',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 510,
            description: 'Analogue d’insuline basale à action prolongée.',
            indications: ['Diabète de type 1', 'Diabète de type 2'],
            contraindications: ['Hypoglycémie'],
            warnings: [
              'Surveiller la glycémie',
              'Ne jamais injecter en IV',
            ],
            sideEffects: ['Hypoglycémie', 'Réactions au site d’injection'],
            dosages: [
              {
                population: 'adult',
                indication: 'Diabète',
                dose: 'selon schéma individualisé',
                frequency: '1 fois/jour à heure fixe',
              },
            ],
            patientInformation:
              'Apprenez la technique d’injection. Ayez toujours du sucre sur vous.',
            professionalInformation:
              'Insuline basale. Titration selon glycémies à jeun.',
            related: [MED.met],
          },
          {
            id: MED.salb,
            bdpmId: '60007733',
            name: 'Salbutamol',
            brandName: 'Ventoline',
            genericName: 'Salbutamol',
            strength: '100 µg/dose',
            dosageForm: 'Inhalateur',
            route: 'inhalation',
            atcCode: 'R03AC02',
            therapeuticClass: 'Bêta-2 agoniste courte durée',
            category: 'respiratory',
            manufacturer: 'GSK',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 700,
            description: 'Bronchodilatateur de secours pour bronchospasme.',
            indications: ['Asthme', 'BPCO', 'Crise d’asthme'],
            contraindications: ['Hypersensibilité au salbutamol'],
            warnings: [
              'Si usage fréquent : revoir le traitement de fond',
              'Technique d’inhalation essentielle',
            ],
            sideEffects: ['Tremblements', 'Tachycardie'],
            dosages: [
              {
                population: 'adult',
                indication: 'Crise',
                dose: '1–2 bouffées',
                frequency: 'selon besoin (max 8–10/j)',
              },
            ],
            patientInformation:
              'Secouez l’inhalateur. Rincez la bouche si associé à un corticoïde.',
            professionalInformation:
              'SABA. Réévaluer si > 2 utilisations/semaine.',
            related: [] as string[],
          },
          {
            id: MED.omep,
            bdpmId: '60008844',
            name: 'Oméprazole',
            brandName: 'Mopral',
            genericName: 'Oméprazole',
            strength: '20 mg',
            dosageForm: 'Gélule',
            route: 'oral',
            atcCode: 'A02BC01',
            therapeuticClass: 'Inhibiteur de la pompe à protons',
            category: 'gastroenterology',
            manufacturer: 'AstraZeneca',
            prescriptionRequired: false,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'caution',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 690,
            description: 'IPP pour RGO et ulcère gastroduodénal.',
            indications: ['RGO', 'Ulcère', 'Protection gastrique'],
            contraindications: ['Hypersensibilité aux IPP'],
            warnings: [
              'Traitement prolongé : risque de carences',
              'Interactions avec le clopidogrel (autres IPP)',
            ],
            sideEffects: ['Céphalées', 'Diarrhée', 'Douleurs abdominales'],
            dosages: [
              {
                population: 'adult',
                indication: 'RGO',
                dose: '20 mg',
                frequency: '1 fois/jour le matin',
              },
            ],
            patientInformation:
              'Avalez la gélule entière, de préférence le matin à jeun.',
            professionalInformation:
              'Inhibe la pompe H+/K+ ATPase. Durée selon indication.',
            related: [] as string[],
          },
          {
            id: MED.ator,
            bdpmId: '60009955',
            name: 'Atorvastatine',
            brandName: 'Tahor',
            genericName: 'Atorvastatine',
            strength: '20 mg',
            dosageForm: 'Comprimé',
            route: 'oral',
            atcCode: 'C10AA05',
            therapeuticClass: 'Statines (inhibiteurs HMG-CoA réductase)',
            category: 'cardiology',
            manufacturer: 'Pfizer',
            prescriptionRequired: true,
            pregnancySafety: 'contraindicated',
            breastfeedingSafety: 'contraindicated',
            pediatricApproved: false,
            geriatricApproved: true,
            searchCount: 730,
            description:
              'Statine pour hypercholestérolémie et réduction du risque cardiovasculaire.',
            indications: [
              'Hypercholestérolémie',
              'Prévention cardiovasculaire',
            ],
            contraindications: [
              'Grossesse',
              'Allaitement',
              'Maladie hépatique active',
            ],
            warnings: [
              'Surveiller CPK et transaminases',
              'Signaler douleurs musculaires',
            ],
            sideEffects: ['Myalgies', 'Troubles digestifs'],
            dosages: [
              {
                population: 'adult',
                indication: 'Hypercholestérolémie',
                dose: '10–20 mg',
                frequency: '1 fois/jour le soir',
              },
            ],
            patientInformation:
              'Évitez le pamplemousse. Signalez toute douleur musculaire inhabituelle.',
            professionalInformation:
              'Titration selon LDL-cible. Interactions CYP3A4.',
            related: [] as string[],
          },
        ];

        for (const m of meds) {
          await tx.medicationCatalog.upsert({
            where: { id: m.id },
            create: {
              id: m.id,
              tenantId: DEMO_TENANT_ID,
              bdpmId: m.bdpmId,
              name: m.name,
              brandName: m.brandName,
              genericName: m.genericName,
              strength: m.strength,
              dosageForm: m.dosageForm,
              route: m.route,
              atcCode: m.atcCode,
              therapeuticClass: m.therapeuticClass,
              category: m.category,
              manufacturer: m.manufacturer,
              prescriptionRequired: m.prescriptionRequired,
              pregnancySafety: m.pregnancySafety,
              breastfeedingSafety: m.breastfeedingSafety,
              pediatricApproved: m.pediatricApproved,
              geriatricApproved: m.geriatricApproved,
              searchCount: m.searchCount,
              description: m.description,
              activeIngredients: [m.genericName],
              indications: m.indications,
              contraindications: m.contraindications,
              warnings: m.warnings,
              sideEffects: m.sideEffects,
              storage: 'Conserver à température ambiante, à l’abri de l’humidité',
              patientInformation: m.patientInformation,
              professionalInformation: m.professionalInformation,
              references: ['Base BDPM démo Med’ease'],
              dosages: m.dosages,
              interactions: [],
              relatedMedicationIds: m.related,
              createdBy: DEMO_ADMIN_ID,
            },
            update: {
              name: m.name,
              brandName: m.brandName,
              genericName: m.genericName,
              strength: m.strength,
              dosageForm: m.dosageForm,
              therapeuticClass: m.therapeuticClass,
              description: m.description,
              searchCount: m.searchCount,
              activeIngredients: [m.genericName],
              indications: m.indications,
              contraindications: m.contraindications,
              warnings: m.warnings,
              sideEffects: m.sideEffects,
              dosages: m.dosages,
              storage: 'Conserver à température ambiante, à l’abri de l’humidité',
              patientInformation: m.patientInformation,
              professionalInformation: m.professionalInformation,
              relatedMedicationIds: m.related,
              available: true,
              updatedBy: DEMO_ADMIN_ID,
            },
          });
        }
      });
    } finally {
      await prisma.$disconnect();
    }
  },
};
