import type { SeedModule } from '../types';

const DEMO_TENANT_ID = '01930000-0000-7000-8000-000000000001';
const DEMO_ADMIN_ID = '01930000-0000-7000-8000-000000000101';

const FAC_PARIS = '01930000-0000-7000-8000-000000000201';
const FAC_LYON = '01930000-0000-7000-8000-000000000202';
const FAC_TOUR = '01930000-0000-7000-8000-000000000203';
const PRO_MARTIN = '01930000-0000-7000-8000-000000000501';
const PRO_BERNARD = '01930000-0000-7000-8000-000000000502';
const PRO_DUPONT = '01930000-0000-7000-8000-000000000503';
const PHARM = '01930000-0000-7000-8000-000000000701';
const TRANSPORT = '01930000-0000-7000-8000-000000000801';

const MED = {
  para: '01930000-0000-7000-8000-000000000e01',
  ibu: '01930000-0000-7000-8000-000000000e02',
  amox: '01930000-0000-7000-8000-000000000e03',
  met: '01930000-0000-7000-8000-000000000e04',
  ins: '01930000-0000-7000-8000-000000000e05',
  salb: '01930000-0000-7000-8000-000000000e06',
  omep: '01930000-0000-7000-8000-000000000e07',
  ator: '01930000-0000-7000-8000-000000000e08',
} as const;

export const directoryMedicalLibrarySeed: SeedModule = {
  name: 'directory-medical-library',
  async run(ctx) {
    if (ctx.dryRun) return;

    const { PrismaClient, runInSystemTransaction } =
      await import('@medease/prisma');
    type TransactionClient = Parameters<
      Parameters<typeof runInSystemTransaction>[1]
    >[0];
    const prisma = new PrismaClient();

    try {
      await runInSystemTransaction(prisma, async (tx: TransactionClient) => {
        const providers = [
          {
            id: PRO_DUPONT,
            type: 'professional' as const,
            name: 'Dr. Marie Dupont',
            title: 'Médecin généraliste',
            specialty: 'General Practice',
            medicalSpecialty: 'Médecine générale',
            street: '22 Rue de Rivoli',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75004',
            phone: '+33 1 42 77 88 99',
            distanceKm: 0.8,
            availability: 'Available today',
            teleconsultation: true,
            associatedFacilityIds: [FAC_PARIS],
          },
          {
            id: PRO_MARTIN,
            type: 'professional' as const,
            name: 'Dr. Jean-Luc Martin',
            title: 'Cardiologue',
            specialty: 'Cardiology',
            medicalSpecialty: 'Cardiologie',
            street: "47 Boulevard de l'Hôpital",
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 42 16 00 10',
            distanceKm: 1.2,
            availability: 'Open now',
            teleconsultation: true,
            associatedFacilityIds: [FAC_PARIS],
          },
          {
            id: PRO_BERNARD,
            type: 'professional' as const,
            name: 'Dr. Sophie Bernard',
            title: 'Endocrinologue',
            specialty: 'Endocrinology',
            medicalSpecialty: 'Endocrinologie',
            street: 'Place d’Arsonval',
            city: 'Lyon',
            department: 'Rhône',
            postalCode: '69003',
            phone: '+33 4 72 11 70 00',
            distanceKm: 5.4,
            availability: 'Available today',
            teleconsultation: false,
            associatedFacilityIds: [FAC_LYON],
          },
          {
            id: FAC_PARIS,
            type: 'facility' as const,
            name: 'Pitié-Salpêtrière',
            facilityType: 'Centre hospitalier',
            finessNumber: '750000001',
            street: "47-83 Boulevard de l'Hôpital",
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 42 16 00 00',
            distanceKm: 1.1,
            availability: 'Open now',
            emergencyServices: true,
            services: ['Emergency', 'Imaging', 'Laboratory'],
          },
          {
            id: FAC_LYON,
            type: 'facility' as const,
            name: 'Édouard Herriot',
            facilityType: 'Centre hospitalier',
            finessNumber: '690000001',
            street: '5 Place d’Arsonval',
            city: 'Lyon',
            department: 'Rhône',
            postalCode: '69003',
            phone: '+33 4 72 11 70 00',
            distanceKm: 5.0,
            availability: 'Open now',
            emergencyServices: true,
            services: ['Emergency', 'Surgery'],
          },
          {
            id: FAC_TOUR,
            type: 'facility' as const,
            name: 'CHU de Tours',
            facilityType: 'Centre hospitalier universitaire',
            finessNumber: '370000001',
            street: '2 Boulevard Tonnellé',
            city: 'Tours',
            department: 'Indre-et-Loire',
            postalCode: '37000',
            phone: '+33 2 47 47 47 47',
            distanceKm: 12.0,
            availability: 'Open now',
            emergencyServices: true,
            services: ['Emergency', 'Maternity'],
          },
          {
            id: PHARM,
            type: 'pharmacy' as const,
            name: 'Pharmacie du Marais',
            facilityType: 'Officine',
            street: '12 Rue des Archives',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75004',
            phone: '+33 1 42 72 11 22',
            distanceKm: 0.5,
            availability: 'Open now',
            services: ['Dispensing', 'Vaccination'],
          },
          {
            id: TRANSPORT,
            type: 'transport' as const,
            name: 'MedEase Ambulance Paris',
            facilityType: 'Transport sanitaire',
            street: '8 Rue de Tolbiac',
            city: 'Paris',
            department: 'Paris',
            postalCode: '75013',
            phone: '+33 1 44 00 00 00',
            distanceKm: 2.0,
            availability: '24/7 dispatch',
            emergencyServices: true,
            services: ['VSL', 'Ambulance', 'Inter-hospital transfer'],
          },
        ];

        for (const p of providers) {
          await tx.directoryProvider.upsert({
            where: { id: p.id },
            create: {
              id: p.id,
              tenantId: DEMO_TENANT_ID,
              type: p.type,
              name: p.name,
              title: 'title' in p ? p.title : undefined,
              specialty: 'specialty' in p ? p.specialty : undefined,
              medicalSpecialty:
                'medicalSpecialty' in p ? p.medicalSpecialty : undefined,
              facilityType: 'facilityType' in p ? p.facilityType : undefined,
              finessNumber: 'finessNumber' in p ? p.finessNumber : undefined,
              street: p.street,
              city: p.city,
              department: p.department,
              postalCode: p.postalCode,
              country: 'France',
              distanceKm: p.distanceKm,
              phone: p.phone,
              availability: p.availability,
              status: 'stable',
              languages: ['French'],
              services: 'services' in p && p.services ? p.services : [],
              teleconsultation:
                'teleconsultation' in p ? Boolean(p.teleconsultation) : false,
              emergencyServices:
                'emergencyServices' in p ? Boolean(p.emergencyServices) : false,
              associatedFacilityIds:
                'associatedFacilityIds' in p && p.associatedFacilityIds
                  ? p.associatedFacilityIds
                  : [],
              createdBy: DEMO_ADMIN_ID,
            },
            update: {
              name: p.name,
              phone: p.phone,
              availability: p.availability,
              active: true,
              updatedBy: DEMO_ADMIN_ID,
            },
          });
        }

        const meds = [
          {
            id: MED.para,
            bdpmId: '60002283',
            name: 'Paracetamol',
            brandName: 'Doliprane',
            genericName: 'Paracetamol',
            strength: '500 mg',
            dosageForm: 'Tablet',
            route: 'oral',
            atcCode: 'N02BE01',
            therapeuticClass: 'Analgesics, non-opioid',
            category: 'pain_relief',
            manufacturer: 'Sanofi',
            prescriptionRequired: false,
            pregnancySafety: 'caution',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 980,
            description: 'Analgesic and antipyretic for mild to moderate pain.',
            related: [MED.ibu],
          },
          {
            id: MED.ibu,
            bdpmId: '60004121',
            name: 'Ibuprofen',
            brandName: 'Advil',
            genericName: 'Ibuprofen',
            strength: '400 mg',
            dosageForm: 'Tablet',
            route: 'oral',
            atcCode: 'M01AE01',
            therapeuticClass: 'NSAID',
            category: 'pain_relief',
            manufacturer: 'Pfizer',
            prescriptionRequired: false,
            pregnancySafety: 'contraindicated',
            breastfeedingSafety: 'caution',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 760,
            description: 'NSAID for pain, inflammation, and fever.',
            related: [MED.para],
          },
          {
            id: MED.amox,
            bdpmId: '60001990',
            name: 'Amoxicillin',
            brandName: 'Clamoxyl',
            genericName: 'Amoxicillin',
            strength: '1 g',
            dosageForm: 'Capsule',
            route: 'oral',
            atcCode: 'J01CA04',
            therapeuticClass: 'Penicillins',
            category: 'antibiotics',
            manufacturer: 'GSK',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 640,
            description: 'Broad-spectrum penicillin antibiotic.',
            related: [] as string[],
          },
          {
            id: MED.met,
            bdpmId: '60005512',
            name: 'Metformin',
            brandName: 'Glucophage',
            genericName: 'Metformin',
            strength: '850 mg',
            dosageForm: 'Tablet',
            route: 'oral',
            atcCode: 'A10BA02',
            therapeuticClass: 'Biguanides',
            category: 'diabetes',
            manufacturer: 'Merck',
            prescriptionRequired: true,
            pregnancySafety: 'caution',
            breastfeedingSafety: 'caution',
            pediatricApproved: false,
            geriatricApproved: true,
            searchCount: 820,
            description: 'First-line oral antidiabetic for type 2 diabetes.',
            related: [MED.ins],
          },
          {
            id: MED.ins,
            bdpmId: '60006601',
            name: 'Insulin glargine',
            brandName: 'Lantus',
            genericName: 'Insulin glargine',
            strength: '100 units/mL',
            dosageForm: 'Injection',
            route: 'injection',
            atcCode: 'A10AE04',
            therapeuticClass: 'Long-acting insulin',
            category: 'diabetes',
            manufacturer: 'Sanofi',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 510,
            description: 'Long-acting basal insulin analog.',
            related: [MED.met],
          },
          {
            id: MED.salb,
            bdpmId: '60007733',
            name: 'Salbutamol',
            brandName: 'Ventoline',
            genericName: 'Salbutamol',
            strength: '100 µg/dose',
            dosageForm: 'Inhaler',
            route: 'inhalation',
            atcCode: 'R03AC02',
            therapeuticClass: 'Short-acting beta-agonist',
            category: 'respiratory',
            manufacturer: 'GSK',
            prescriptionRequired: true,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'safe',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 700,
            description: 'Rescue inhaler for bronchospasm.',
            related: [] as string[],
          },
          {
            id: MED.omep,
            bdpmId: '60008844',
            name: 'Omeprazole',
            brandName: 'Mopral',
            genericName: 'Omeprazole',
            strength: '20 mg',
            dosageForm: 'Capsule',
            route: 'oral',
            atcCode: 'A02BC01',
            therapeuticClass: 'Proton pump inhibitor',
            category: 'gastroenterology',
            manufacturer: 'AstraZeneca',
            prescriptionRequired: false,
            pregnancySafety: 'safe',
            breastfeedingSafety: 'caution',
            pediatricApproved: true,
            geriatricApproved: true,
            searchCount: 690,
            description: 'PPI for GERD and peptic ulcer disease.',
            related: [] as string[],
          },
          {
            id: MED.ator,
            bdpmId: '60009955',
            name: 'Atorvastatin',
            brandName: 'Tahor',
            genericName: 'Atorvastatin',
            strength: '20 mg',
            dosageForm: 'Tablet',
            route: 'oral',
            atcCode: 'C10AA05',
            therapeuticClass: 'HMG-CoA reductase inhibitors',
            category: 'cardiology',
            manufacturer: 'Pfizer',
            prescriptionRequired: true,
            pregnancySafety: 'contraindicated',
            breastfeedingSafety: 'contraindicated',
            pediatricApproved: false,
            geriatricApproved: true,
            searchCount: 730,
            description:
              'Statin for hypercholesterolemia and CV risk reduction.',
            related: [] as string[],
          },
        ];

        for (const m of meds) {
          await tx.medicationCatalog.upsert({
            where: { id: m.id },
            create: {
              id: m.id,
              tenantId: DEMO_TENANT_ID,
              bdpmId: m.bdpmId,
              name: m.name,
              brandName: m.brandName,
              genericName: m.genericName,
              strength: m.strength,
              dosageForm: m.dosageForm,
              route: m.route,
              atcCode: m.atcCode,
              therapeuticClass: m.therapeuticClass,
              category: m.category,
              manufacturer: m.manufacturer,
              prescriptionRequired: m.prescriptionRequired,
              pregnancySafety: m.pregnancySafety,
              breastfeedingSafety: m.breastfeedingSafety,
              pediatricApproved: m.pediatricApproved,
              geriatricApproved: m.geriatricApproved,
              searchCount: m.searchCount,
              description: m.description,
              activeIngredients: [m.genericName],
              indications: [m.therapeuticClass],
              contraindications: [],
              warnings: [],
              sideEffects: [],
              storage: 'Store as labeled',
              patientInformation: m.description,
              professionalInformation: m.description,
              references: ['BDPM demo catalog'],
              dosages: [
                {
                  population: 'adult',
                  indication: m.therapeuticClass,
                  dose: m.strength,
                  frequency: 'as directed',
                },
              ],
              interactions: [],
              relatedMedicationIds: m.related,
              createdBy: DEMO_ADMIN_ID,
            },
            update: {
              name: m.name,
              brandName: m.brandName,
              searchCount: m.searchCount,
              relatedMedicationIds: m.related,
              available: true,
              updatedBy: DEMO_ADMIN_ID,
            },
          });
        }
      });
    } finally {
      await prisma.$disconnect();
    }
  },
};
