export const ROUTES = {
  home: '/',
  about: '/about',
  features: '/features',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  help: '/help',
  status: '/status',
  notFound: '/404',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  logout: '/logout',
  sessionExpired: '/session-expired',
  forbidden: '/403',
  serverError: '/500',
  offline: '/offline',
  designSystem: '/design-system',
  patient: {
    root: '/patient',
    login: '/patient/login',
    appointments: '/patient/appointments',
    appointmentsBook: '/patient/appointments/book',
    appointmentsCalendar: '/patient/appointments/calendar',
    appointmentsUpcoming: '/patient/appointments/upcoming',
    appointmentsHistory: '/patient/appointments/history',
    appointmentDetails: '/patient/appointments/:appointmentId',
    medicalRecords: '/patient/medical-records',
    records: '/patient/records',
    recordsProfile: '/patient/records/profile',
    recordsSummary: '/patient/records/summary',
    recordsVitals: '/patient/records/vitals',
    recordsTimeline: '/patient/records/timeline',
    medications: '/patient/medications',
    /** @deprecated Legacy patient medication sub-routes */
    medicationsToday: '/patient/medications/today',
    medicationsCalendar: '/patient/medications/calendar',
    medicationsHistory: '/patient/medications/history',
    medicationsRefills: '/patient/medications/refills',
    medicationsReminders: '/patient/medications/reminders',
    /** @deprecated Legacy dose logs route */
    medicationsLogs: '/patient/medications/logs',
    medicationDetails: '/patient/medications/:medicationId',
    medicalLibrary: '/patient/medical-library',
    medicalLibrarySearch: '/patient/medical-library/search',
    medicalLibraryCategories: '/patient/medical-library/categories',
    carePlan: '/patient/care-plan',
    carePlanGoals: '/patient/care-plan/goals',
    carePlanTasks: '/patient/care-plan/tasks',
    carePlanTimeline: '/patient/care-plan/timeline',
    carePlanTeam: '/patient/care-plan/team',
    carePlanProgress: '/patient/care-plan/progress',
    carePlanEducation: '/patient/care-plan/education',
    laboratory: '/patient/laboratory',
    laboratoryOrders: '/patient/laboratory/orders',
    laboratoryResults: '/patient/laboratory/results',
    laboratoryHistory: '/patient/laboratory/history',
    laboratoryTrends: '/patient/laboratory/trends',
    laboratoryResultDetail: '/patient/laboratory/:resultId',
    radiology: '/patient/radiology',
    radiologyHistory: '/patient/radiology/history',
    radiologyStudy: '/patient/radiology/:studyId',
    radiologyReport: '/patient/radiology/report/:reportId',
    monitoring: '/patient/monitoring',
    vitals: '/patient/vitals',
    observations: '/patient/observations',
    rpm: '/patient/rpm',
    monitoringDetail: '/patient/monitoring/:observationId',
    telemedicine: '/patient/telemedicine',
    telemedicineUpcoming: '/patient/telemedicine/upcoming',
    telemedicineHistory: '/patient/telemedicine/history',
    telemedicineSession: '/patient/telemedicine/session/:sessionId',
    telemedicineDeviceCheck: '/patient/telemedicine/device-check',
    billing: '/patient/billing',
    patientInvoices: '/patient/invoices',
    patientPayments: '/patient/payments',
    patientInsurance: '/patient/insurance',
    patientReceipts: '/patient/receipts',
    /** @deprecated Use carePlan */
    carePathways: '/patient/care-plan',
    transfers: '/patient/transfers',
    profile: '/patient/profile',
    settings: '/patient/settings',
    messages: '/patient/messages',
    notifications: '/patient/notifications',
    documents: '/patient/documents',
    admissions: '/patient/admissions',
    vaccinations: '/patient/vaccinations',
    insurance: '/patient/insurance',
    emergencyProfile: '/patient/emergency-profile',
    healthcareDirectory: '/patient/directory',
    directory: '/patient/directory',
    directoryProfessionals: '/patient/directory/professionals',
    directoryFacilities: '/patient/directory/facilities',
    directoryPharmacies: '/patient/directory/pharmacies',
    directoryTransport: '/patient/directory/transport',
  },
  professional: {
    root: '/professional',
    patients: '/professional/patients',
    patientRecord: '/professional/patient/:patientId',
    consultations: '/professional/consultations',
    transfers: '/professional/transfers',
    reports: '/professional/reports',
    schedules: '/professional/schedule',
    calendar: '/professional/calendar',
    appointments: '/professional/appointments',
    appointmentDetails: '/professional/appointments/:appointmentId',
    careCoordination: '/professional/care-coordination',
    admissions: '/professional/admissions',
    documents: '/professional/documents',
    tasks: '/professional/tasks',
    notifications: '/professional/notifications',
    messages: '/professional/messages',
    profile: '/professional/profile',
    settings: '/professional/settings',
    directory: '/professional/directory',
    medicalLibrary: '/professional/medical-library',
    prescriptions: '/professional/prescriptions',
    patientMedications: '/professional/patient/:patientId/medications',
    patientPrescribe: '/professional/patient/:patientId/prescribe',
    medications: '/professional/medications',
    professionalPrescriptions: '/professional/prescriptions',
    reconciliation: '/professional/reconciliation',
    professionalAdministration: '/professional/administration',
    medicationAnalytics: '/professional/analytics',
    patientMedicationHistory: '/professional/patient/:patientId/history',
    carePlans: '/professional/care-plans',
    patientCarePlan: '/professional/patient/:patientId/care-plan',
    patientCareTasks: '/professional/patient/:patientId/tasks',
    patientCareGoals: '/professional/patient/:patientId/goals',
    clinicalPathways: '/professional/pathways',
    laboratory: '/professional/laboratory',
    patientLaboratory: '/professional/patient/:patientId/laboratory',
    laboratoryOrders: '/professional/laboratory/orders',
    laboratoryResults: '/professional/results',
    laboratoryCritical: '/professional/laboratory/critical',
    laboratoryMicrobiology: '/professional/microbiology',
    laboratoryPathology: '/professional/pathology',
    radiology: '/professional/radiology',
    worklist: '/professional/worklist',
    radiologyReports: '/professional/reports',
    radiologyViewer: '/professional/viewer/:studyId',
    radiologyCompare: '/professional/compare',
    patientRadiology: '/professional/patient/:patientId/radiology',
    monitoring: '/professional/monitoring',
    monitoringAlerts: '/professional/alerts',
    monitoringDevices: '/professional/devices',
    monitoringAnalytics: '/professional/analytics',
    patientMonitoring: '/professional/patient/:patientId/monitoring',
    telemedicine: '/professional/telemedicine',
    waitingRoom: '/professional/waiting-room',
    currentSession: '/professional/current-session',
    telemedicineHistory: '/professional/telemedicine/history',
    providerAvailability: '/professional/availability',
    telemedicineSession: '/professional/session/:sessionId',
    professionalBilling: '/professional/billing',
    professionalClaims: '/professional/claims',
    professionalBillingPayments: '/professional/payments',
    professionalRevenue: '/professional/revenue',
    workforce: '/professional/workforce',
    workforceSchedule: '/professional/workforce-schedule',
    professionalAttendance: '/professional/attendance',
    professionalTraining: '/professional/training',
    professionalPerformance: '/professional/performance',
    professionalFacilities: '/professional/facilities',
    professionalEquipment: '/professional/equipment',
    professionalMaintenance: '/professional/maintenance',
  },
  facility: {
    root: '/facility',
    beds: '/facility/beds',
    admissions: '/facility/admissions',
    transfers: '/facility/transfers',
    staff: '/facility/staff',
    capacity: '/facility/capacity',
    resources: '/facility/resources',
    schedule: '/facility/schedule',
    calendar: '/facility/calendar',
    patients: '/facility/patients',
    reports: '/facility/reports',
    analytics: '/facility/analytics',
    documents: '/facility/documents',
    settings: '/facility/settings',
    directory: '/facility/directory',
    medicalLibrary: '/facility/medical-library',
    medications: '/facility/medications',
    emar: '/facility/emar',
    facilityAdministration: '/facility/administration',
    /** @deprecated Use medications */
    medicationBoard: '/facility/medication-board',
    /** @deprecated Use administration */
    medicationAdministration: '/facility/medication-administration',
    carePlans: '/facility/care-plans',
    careCoordination: '/facility/coordination',
    wardCare: '/facility/ward-care',
    laboratory: '/facility/laboratory',
    labDashboard: '/facility/dashboard',
    specimens: '/facility/specimens',
    labQuality: '/facility/quality',
    labOrders: '/facility/orders',
    radiology: '/facility/radiology',
    imagingDashboard: '/facility/dashboard',
    facilityImaging: '/facility/imaging',
    imagingDevices: '/facility/devices',
    monitoring: '/facility/monitoring',
    monitoringDashboard: '/facility/dashboard',
    monitoringDevices: '/facility/devices',
    monitoringAlerts: '/facility/alerts',
    facilityTelemedicine: '/facility/telemedicine',
    telemedicineSessions: '/facility/sessions',
    telemedicineProviders: '/facility/providers',
    telemedicineAnalytics: '/facility/analytics',
    facilityBilling: '/facility/billing',
    facilityRevenue: '/facility/revenue',
    facilityClaims: '/facility/claims',
    facilityBillingPayments: '/facility/payments',
    facilityInventory: '/facility/inventory',
    facilityAssets: '/facility/assets',
    facilityWarehouse: '/facility/warehouse',
    facilityProcurement: '/facility/procurement',
    facilityReceiving: '/facility/receiving',
    facilityDeliveries: '/facility/deliveries',
    facilityWorkforce: '/facility/workforce',
    facilityStaff: '/facility/staff',
    facilityScheduling: '/facility/scheduling',
    facilityAttendance: '/facility/attendance',
    facilityLeave: '/facility/leave',
    facilityTraining: '/facility/training',
    facilityFacilitiesMgmt: '/facility/facilities',
    facilityBuildings: '/facility/buildings',
    facilityCmmsAssets: '/facility/facility-assets',
    facilityMaintenance: '/facility/maintenance',
    facilityUtilities: '/facility/utilities',
    facilityEnvironment: '/facility/environment',
    facilityHousekeeping: '/facility/housekeeping',
    facilityFleet: '/facility/fleet',
  },
  pharmacy: {
    root: '/pharmacy',
    medications: '/pharmacy/medications',
    inventory: '/pharmacy/inventory',
    stock: '/pharmacy/stock',
    expiry: '/pharmacy/expiry',
    procurement: '/pharmacy/procurement',
    purchaseOrders: '/pharmacy/purchase-orders',
    pharmacySuppliers: '/pharmacy/suppliers',
    prescriptions: '/pharmacy/prescriptions',
    medicationRequests: '/pharmacy/medication-requests',
    dispensing: '/pharmacy/dispensing',
    pharmacyRefills: '/pharmacy/refills',
    interactions: '/pharmacy/interactions',
    patients: '/pharmacy/patients',
    reports: '/pharmacy/reports',
    notifications: '/pharmacy/notifications',
    profile: '/pharmacy/profile',
    settings: '/pharmacy/settings',
    medicalLibrary: '/pharmacy/medical-library',
    /** @deprecated Alias for dispensing */
    pharmacyDispensing: '/pharmacy/dispensing',
  },
  transport: {
    root: '/transport',
    transferRequests: '/transport/transfer-requests',
    vehicles: '/transport/vehicles',
    drivers: '/transport/drivers',
    schedules: '/transport/schedules',
    patients: '/transport/patients',
    facilities: '/transport/facilities',
    history: '/transport/history',
    reports: '/transport/reports',
    settings: '/transport/settings',
  },
  admin: {
    root: '/admin',
    users: '/admin/users',
    organizations: '/admin/organizations',
    facilities: '/admin/facilities',
    healthcareProfessionals: '/admin/healthcare-professionals',
    patients: '/admin/patients',
    roles: '/admin/roles',
    permissions: '/admin/permissions',
    auditLogs: '/admin/audit-logs',
    featureFlags: '/admin/feature-flags',
    systemStatus: '/admin/system-status',
    analytics: '/admin/analytics',
    notifications: '/admin/notifications',
    settings: '/admin/settings',
    directory: '/admin/directory',
    medicalLibrary: '/admin/medical-library',
    appointments: '/admin/appointments',
    calendar: '/admin/calendar',
    scheduling: '/admin/scheduling',
    adminMedications: '/admin/medications',
    adminPrescriptions: '/admin/prescriptions',
    medicationAnalytics: '/admin/medication-analytics',
    formulary: '/admin/formulary',
    carePlans: '/admin/care-plans',
    careQuality: '/admin/care-quality',
    populationHealth: '/admin/population-health',
    careAnalytics: '/admin/care-analytics',
    laboratory: '/admin/laboratory',
    laboratoryAnalytics: '/admin/laboratory/analytics',
    laboratoryInstruments: '/admin/laboratory/instruments',
    laboratoryQuality: '/admin/laboratory/quality',
    radiology: '/admin/radiology',
    radiologyAnalytics: '/admin/radiology/analytics',
    radiologyDevices: '/admin/radiology/devices',
    radiologyWorkload: '/admin/radiology/workload',
    monitoring: '/admin/monitoring',
    adminRpm: '/admin/rpm',
    monitoringAnalytics: '/admin/monitoring/analytics',
    adminMonitoringDevices: '/admin/devices',
    adminTelemedicine: '/admin/telemedicine',
    adminTelemedicineAnalytics: '/admin/telemedicine/analytics',
    adminTelemedicineProviders: '/admin/providers',
    platformHealth: '/admin/platform-health',
    adminBilling: '/admin/billing',
    adminRevenue: '/admin/revenue',
    financialReports: '/admin/financial-reports',
    adminClaims: '/admin/claims',
    adminBillingPayments: '/admin/payments',
    adminInventory: '/admin/inventory',
    adminProcurement: '/admin/procurement',
    adminPurchaseOrders: '/admin/purchase-orders',
    adminRFQs: '/admin/rfqs',
    adminContracts: '/admin/contracts',
    adminSuppliers: '/admin/suppliers',
    adminBudgets: '/admin/budgets',
    adminApprovals: '/admin/approvals',
    procurementAnalytics: '/admin/analytics',
    inventoryAnalytics: '/admin/inventory-analytics',
    adminWorkforce: '/admin/workforce',
    adminEmployees: '/admin/employees',
    adminDepartments: '/admin/departments',
    adminOrganization: '/admin/organization',
    adminSchedules: '/admin/schedules',
    adminPayroll: '/admin/payroll',
    adminPerformance: '/admin/performance',
    adminCredentials: '/admin/credentials',
    workforceAnalytics: '/admin/workforce-analytics',
    adminFacilitiesMgmt: '/admin/facilities',
    adminFacilitiesBuildings: '/admin/buildings',
    adminFacilitiesCmmsAssets: '/admin/facilities-assets',
    adminWorkOrders: '/admin/work-orders',
    adminCalibration: '/admin/calibration',
    adminFacilitiesVendors: '/admin/vendors',
    adminFacilitiesContracts: '/admin/contracts',
    facilitiesAnalytics: '/admin/facilities-analytics',
    adminSystemHealth: '/admin/system-health',
    pharmacyBilling: '/pharmacy/billing',
    pharmacyBillingPayments: '/pharmacy/payments',
    pharmacyClaims: '/pharmacy/claims',
  },
} as const;

export type PortalId =
  'patient' | 'professional' | 'facility' | 'pharmacy' | 'transport' | 'admin';

export const PORTAL_PATHS: Record<PortalId, string> = {
  patient: ROUTES.patient.root,
  professional: ROUTES.professional.root,
  facility: ROUTES.facility.root,
  pharmacy: ROUTES.pharmacy.root,
  transport: ROUTES.transport.root,
  admin: ROUTES.admin.root,
};

export const AUTH_ROUTES = [
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
  ROUTES.resetPassword,
  ROUTES.verifyEmail,
  ROUTES.logout,
  ROUTES.sessionExpired,
] as const;

export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.about,
  ROUTES.features,
  ROUTES.contact,
  ROUTES.privacy,
  ROUTES.terms,
  ROUTES.help,
  ROUTES.status,
  ROUTES.notFound,
  ...AUTH_ROUTES,
] as const;
